USE hrms;

SELECT * FROM departments;

SELECT * FROM designations;

SELECT * FROM emp;

UPDATE emp
SET salary = 50000
WHERE ï»¿employee_id BETWEEN "EMP1" AND "EMP35";

SET SQL_SAFE_UPDATES = 0;

SELECT * FROM departments;

INSERT INTO departments VALUES(1,"IT","SOFTWARE AND HARDWARE");
INSERT INTO departments VALUES(2,"HR","EMPLOYEE ONBOARDING");
INSERT INTO departments VALUES(3,"MANAGMENT","PRODUCT HANDLING");
INSERT INTO departments VALUES(4,"FINANCE","FINANCE");
INSERT INTO departments VALUES(5,"NETWORK","NETWORK AND SECURITY");

SELECT * FROM designations;

INSERT INTO designations VALUES(101,"SOFTWARE ENGINEER",1);
INSERT INTO designations VALUES(102,"BUSINESS ANALYST",2);
INSERT INTO designations VALUES(103,"CONFIGURATION EXPERT",1);
INSERT INTO designations VALUES(104,"SOFTWARE ENGINEER",3);
INSERT INTO designations VALUES(105,"ERP IMPLEMENTATION EXPERT",1);







